services:
  app:
    container_name: habit-tracker
    build: .
    restart: always
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    ports:
      - '127.0.0.1:8080:5000'
    env_file:
      - .env

    volumes:
      - ./db:/srv/db
