
CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  joined TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS events (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  event_name TEXT NOT NULL,
  event_tag TEXT NOT NULL,
  event_type TEXT CHECK(event_type IN ('NUMERIC', 'OCCURENCE')) NOT NULL DEFAULT 'OCCURENCE',
  event_freq TEXT CHECK(event_freq IN ('DAILY', 'WEEKLY')) NOT NULL DEFAULT 'DAILY',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  user_id INTEGER,
  description TEXT,
  FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE IF NOT EXISTS occurences (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  event_id INTEGER,
  occured_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  comment TEXT,
  numeric_value FLOAT,
  FOREIGN KEY (event_id) REFERENCES events(event_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS measurements (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  event_id INTEGER,
  occured_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  value NUMBER NOT NULL,
  FOREIGN KEY (event_id) REFERENCES events(event_id) ON DELETE CASCADE
);


