name: Deploy
on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: pull and restart
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          whoami
          cd /srv/habit-tracker
          ./pull_and_restart.sh
